name: Compilatore WebAssembly per Websim

on:
  workflow_dispatch:

jobs:
  build-wasm:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup Emscripten
        uses: mymindstorm/setup-emsdk@v14
        with:
          version: '3.1.64'

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libsdl2-dev libsdl2-mixer-dev

      - name: Compile Code
        run: |
          mkdir -p build-wasm
          emcc $(find RSDKv4 -name "*.cpp" -o -name "*.c") -O3 -s WASM=1 -s USE_SDL=2 -s USE_SDL_MIXER=2 -s ALLOW_MEMORY_GROWTH=1 -o build-wasm/RSDKv4.js

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: rsdkv4-web-port
          path: build-wasm/
